name = "sp100-financial-tracker"
compatibility_date = "2025-10-04"

# This is a Pages project with static assets and Functions
pages_build_output_dir = "."

# Environment variables for GitHub integration
# Non-sensitive values can be defined here
[vars]
GITHUB_OWNER = "avalidurl"
GITHUB_REPO_NAME = "sp100-financial-tracker"

# GITHUB_TOKEN should remain as an encrypted secret in the Cloudflare Dashboard
# Don't add it here - keep it encrypted in Settings → Environment Variables

