name: Update News and Filings Data

on:
  schedule:
    # Run every 30 minutes during market hours (9 AM - 6 PM ET, Mon-Fri)
    - cron: '*/30 13-22 * * 1-5'  # UTC time (ET +5)
    # Run every 2 hours outside market hours and weekends
    - cron: '0 */2 * * *'
  workflow_dispatch: # Allow manual triggering

jobs:
  update-data:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests python-dateutil
    
    - name: Fetch news and filings data
      env:
        RSS2JSON_API_KEY: ${{ secrets.RSS2JSON_API_KEY }}
      run: python scripts/fetch_news_filings.py
    
    - name: Check for changes
      id: verify-changed-files
      run: |
        if [ -n "$(git status --porcelain)" ]; then
          echo "changed=true" >> $GITHUB_OUTPUT
        else
          echo "changed=false" >> $GITHUB_OUTPUT
        fi
    
    - name: Commit updated data
      if: steps.verify-changed-files.outputs.changed == 'true'
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add data/
        git commit -m "🔄 Auto-update: News and filings data $(date -u +'%Y-%m-%d %H:%M UTC')

        📰 Updated news for all SP100 companies
        📋 Updated SEC filings data
        🤖 Via GitHub Actions (secure API key)
        
        Generated: $(date -u +'%Y-%m-%d %H:%M UTC')"
        git push