name: Update S&P 100 Quarterly Data

on:
  schedule:
    - cron: '0 6 * * 1,4'  # Twice weekly: Mondays & Thursdays at 6 AM UTC
  workflow_dispatch:

jobs:
  update-data:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Verify API key is configured
      run: |
        if [ -z "${{ secrets.FMP_API_KEY }}" ]; then
          echo "ERROR: FMP_API_KEY secret not configured!"
          echo "Please configure the FMP_API_KEY secret in GitHub repository settings."
          exit 1
        fi
        echo "API key secret is properly configured ✓"
    
    - name: Run data collection
      env:
        FMP_API_KEY: ${{ secrets.FMP_API_KEY }}
      run: |
        cd scripts
        python fetch_data.py
    
    - name: Commit and push if changed
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add public/data/
        git diff --staged --quiet || git commit -m "Update S&P 100 quarterly data $(date)"
        git push